language: node_js

node_js:
  - "node"

cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache

before_script:
  - yarn bootstrap

script: yarn run build

after_success:
  - test $TRAVIS_BRANCH = "master" && lerna publish --conventional-commits --yes --access public
  - test $TRAVIS_BRANCH = "master" && lerna run surge
